import random
import tkinter as tk
from tkinter import messagebox

# English words and their Turkish equivalents
word_dict = {
    "Accept": "Kabul etmek",
    "Accuse": "Suçlamak",
    "Achieve": "Başarmak",
    "Acknowledge": "Kabul etmek",
    "Acquire": "Elde etmek",
    "Adapt": "Adapte etmek",
    "Add": "Eklemek",
    "Adjust": "Ayarlamak",
    "Admire": "Hayranlık duymak",
    "Admit": "Kabul, itiraf etmek",
    "Adopt": "Evlat edinmek",
    "Adore": "Beğenmek, bayılmak",
    "Advise": "Öğüt vermek",
    "Afford": "Parası yetmek",
    "Agree": "Aynı fikirde olmak",
    "Aim": "Hedeflemek",
    "Allow": "İzin vermek",
    "Announce": "Anons etmek",
    "Anticipate": "Beklemek, ummak",
    "Apologize": "Özür dilemek",
    "Appear": "Belli olmak, görünmek",
    "Apply": "Uygulamak, başvurmak",
    "Appreciate": "Minnet duymak",
    "Approach": "Yaklaşmak, yaklaşım",
    "Approve": "Onaylamak",
    "Argue": "Tartışmak",
    "Arise": "Meydana çıkmak",
    "Arrange": "Ayarlamak, düzenlemek",
    "Arrive": "Varmak",
    "Ask": "Sormak",
    "Assume": "Üstlenmek",
    "Assure": "Garanti etmek",
    "Attach": "Yapıştırmak, iliştirmek",
    "Attempt": "Kalkışmak",
    "Attend": "Katılmak",
    "Attract": "Cezbetmek, çekmek",
    "Avoid": "Kaçınmak, önlemek",
    "Awake": "Uykudan kalkmak",
    "Bake": "Fırında pişirmek",
    "Be": "Var olmak, bulunmak",
    "Beat": "Dayak atmak, vurmak",
    "Become": "... haline gelmek",
    "Beg": "Yalvarmak",
    "Begin": "Başlamak",
    "Behave": "Davranmak",
    "Believe": "İnanmak",
    "Belong": "Ait olmak",
    "Bet": "İddiaya girmek",
    "Bind": "Sarmak, kaplamak",
    "Bite": "Isırmak",
    "Blow": "Üflemek, esmek",
    "Boil": "Kaynamak",
    "Borrow": "Ödünç almak",
    "Bounce": "Zıplamak, sekmek",
    "Break": "Kırmak, bozmak",
    "Breed": "Doğurmak, yavrulamak",
    "Bring": "Getirmek",
    "Build": "İnşa etmek",
    "Burn": "Yanmak",
    "Buy": "Satın almak",
    "Calculate": "Hesaplamak",
    "Can": "Olabilmek, -a bilmek",
    "Care": "Önem vermek, bakım",
    "Carry": "Taşımak",
    "Catch": "Yakalamak",
    "Celebrate": "Kutlamak",
    "Change": "Değiştirmek",
    "Choose": "Seçmek",
    "Claim": "Talep, iddia etmek",
    "Climb": "Tırmanmak",
    "Come": "Gelmek",
    "Commit": "Suç işlemek",
    "Communicate": "İletişim kurmak",
    "Compare": "Karşılaştırmak",
    "Compete": "Rekabet etmek",
    "Complain": "Şikayet etmek",
    "Complete": "Tamamlamak",
    "Concern": "Endişelenmek",
    "Confirm": "Onaylamak",
    "Consent": "Razı olmak",
    "Consider": "Göz önünde bulundurmak",
    "Consist": "-den meydana gelmek",
    "Consult": "Danışmak",
    "Contain": "Kapsamak, içermek",
    "Continue": "Devam etmek",
    "Convince": "İkna etmek",
    "Cook": "Yemek pişirmek",
    "Cost": "Mâl olmak",
    "Count": "Saymak",
    "Create": "Yaratmak",
    "Criticize": "Eleştirmek",
    "Cry": "Ağlamak",
    "Cut": "Kesmek",
    "Dance": "Dans etmek",
    "Deal": "Anlaşma, iş yapmak",
    "Decide": "Karar vermek",
    "Delay": "Gecikmek, ertelemek",
    "Demand": "Talep etmek",
    "Deny": "Reddetmek",
    "Depend": "Bağlı olmak",
    "Describe": "Tanımlamak",
    "Deserve": "Hak etmek",
    "Desire": "Arzulamak",
    "Destroy": "Yok etmek",
    "Determine": "Kararlaştırmak",
    "Develop": "Geliştirmek",
    "Disagree": "Aynı fikirde olmamak",
    "Discover": "Keşfetmek",
    "Discuss": "Tartışmak",
    "Dislike": "Hoşlanmamak",
    "Distribute": "Dağıtmak, bölmek",
    "Do": "Yapmak",
    "Doubt": "Şüphelenmek",
    "Drag": "Sürüklemek",
    "Dream": "Rüya görmek",
    "Drill": "Delmek",
    "Drink": "İçmek",
    "Drive": "Araç sürmek",
    "Drop": "Düşmek, düşürmek",
    "Dry": "Kurutmak",
    "Earn": "Para kazanmak",
    "Eat": "Yemek",
    "Emphasize": "Vurgulamak",
    "Enable": "Olanak vermek",
    "Encourage": "Cesaretlendirmek",
    "Engage": "Nişanlanmak",
    "Enhance": "Arttırmak, yükseltmek",
    "Enjoy": "Tadını çıkarmak",
    "Ensure": "Garantiye almak",
    "Entail": "Şarta bağlamak",
    "Enter": "İçeri girmek",
    "Establish": "Kurmak",
    "Examine": "Muayene etmek",
    "Exist": "Var olmak",
    "Expand": "Yayılmak",
    "Expect": "Ummak",
    "Experiment": "Deney yapmak",
    "Explain": "Açıklamak",
    "Explore": "Keşfetmek, araştırmak",
    "Extend": "Genişletmek, uzatmak",
    "Fail": "Başarısızlığa uğramak",
    "Fall": "Düşmek",
    "Feed": "Beslemek",
    "Feel": "Hissetmek",
    "Flight": "Uçmak",
    "Find": "Bulmak",
    "Finish": "Bitirmek",
    "Fit": "Uymak",
    "Fly": "Uçmak",
    "Fold": "Bükülmek, katlamak",
    "Follow": "Takip etmek",
    "Forbid": "Yasaklamak",
    "Forget": "Unutmak",
    "Forgive": "Affetmek",
    "Freeze": "Donmak",
    "Fry": "Yağda kızartmak",
    "Generate": "Meydana getirmek",
    "Get": "Elde etmek",
    "Give": "Vermek",
    "Go": "Gitmek",
    "Grow": "Büyümek",
    "Hang": "Asmak",
    "Happen": "Olmak, meydana gelmek",
    "Hate": "Nefret etmek",
    "Have": "Sahip olmak",
    "Hear": "Duymak",
    "Hesitate": "Tereddüt etmek",
    "Hide": "Gizlemek",
    "Hit": "Çarpmak",
    "Hold": "Tutmak",
    "Hope": "Umut etmek",
    "Hug": "Sarılmak",
    "Hurry": "Acele etmek",
    "Hurt": "Yaralamak",
    "Identify": "Kimliğini tespit etmek",
    "Ignore": "Görmezden gelmek",
    "Imagine": "Hayal etmek",
    "Impress": "Etkilemek",
    "Improve": "Geliştirmek",
    "Include": "İçermek",
    "Incorporate": "Firma kurmak",
    "Indicate": "İşaret etmek",
    "Inform": "Bilgilendirmek",
    "Insist": "Israr etmek",
    "Install": "Kurmak",
    "Intend": "Niyet etmek",
    "Introduce": "Tanıştırmak",
    "Invest": "Yatırım yapmak",
    "Investigate": "Soruşturmak",
    "Involve": "Kapsamak",
    "Iron": "Ütülemek",
    "Jump": "Zıplamak",
    "Justify": "Haklı göstermek",
    "Keep": "Tutmak, saklamak",
    "Kick": "Tekmelemek",
    "Kiss": "Öpmek",
    "Kneel": "Diz çökmek",
    "Knit": "Örmek",
    "Know": "Bilmek",
    "Lack": "Eksik olmak",
    "Laugh": "Gülmek",
    "Lay": "Sermek",
    "Lean": "Eğilmek, yaşlanmak",
    "Leap": "Sıçramak, atlamak",
    "Learn": "Öğrenmek",
    "Live": "Yaşamak",
    "Leave": "Ayrılmak, terk etmek",
    "Lend": "Ödünç vermek",
    "Lie (in bed)": "Uzanmak",
    "Lie": "Yalan söylemek",
    "Lift": "Kaldırmak",
    "Light": "Işık saçmak, parlatmak",
    "Like": "Beğenmek",
    "Listen": "Dinlemek",
    "Look": "Bakmak",
    "Loose": "Kaybetmek",
    "Love": "Sevmek",
    "Maintain": "Bakım yapmak, devam ettirmek",
    "Make": "Yapmak",
    "Manage": "Yönetmek",
    "Matter": "Önemli olmak",
    "Mean": "Demek istemek, kastetmek",
    "Measure": "Ölçmek",
    "Meet": "Tanışmak",
    "Melt": "Erimek",
    "Mention": "Belirtmek",
    "Mind": "Önemsemek",
    "Miss": "Özlemek",
    "Mix": "Karıştırmak",
    "Must": "Gerekmek, -meli -malı",
    "Need": "İhtiyaç duymak",
    "Neglect": "İhmal etmek",
    "Negotiate": "Pazarlık etmek",
    "Observe": "Gözlemlemek",
    "Obtain": "Elde etmek",
    "Occur": "Meydana gelmek",
    "Offer": "Teklif vermek",
    "Open": "Açmak",
    "Operate": "Ameliyat etmek",
    "Order": "Sipariş vermek",
    "Organize": "Organize etmek",
    "Ought to": "-meli/-malı (yapmalı/bilmeli vb)",
    "Overcome": "Üstesinden gelmek",
    "Overtake": "Yetişip geçmek",
    "Own": "Sahip olmak",
    "Paint": "Boyamak",
    "Participate": "Katılmak",
    "Pay": "Ödemek",
    "Peel": "Soymak",
    "Perform": "Rol yapmak",
    "Persuade": "İkna etmek",
    "Pick up": "Toplamak, almak",
    "Pinch": "Çimdiklemek, sıkmak",
    "Plan": "Planlamak",
    "Play": "Oynamak",
    "Point": "İşaret etmek",
    "Postpone": "Ertelemek",
    "Practice": "Alıştırma yapmak",
    "Prefer": "Tercih etmek",
    "Prepare": "Hazırlamak",
    "Pretend": "Yapar gibi görünmek",
    "Prevent": "Önlemek",
    "Proceed": "İlerlemek",
    "Promise": "Söz vermek",
    "Propose": "Önermek",
    "Protect": "Korumak",
    "Prove": "Kanıtlamak",
    "Pull": "Çekmek",
    "Punch": "Yumruklamak",
    "Pursue": "İzlemek, takip etmek",
    "Push": "İtmek",
    "Put": "Koymak",
    "Qualify": "Nitelendirmek",
    "Quit": "Bırakmak, çıkmak",
    "React": "Tepki göstermek",
    "Read": "Okumak",
    "Realize": "Farkına varmak",
    "Recall": "Hatırlamak",
    "Receive": "Teslim almak",
    "Recollect": "Anımsamak",
    "Recommend": "Tavsiye etmek",
    "Reduce": "Azaltmak",
    "Refer": "Anmak, bahsetmek",
    "Reflect": "Yansıtmak",
    "Refuse": "Reddetmek",
    "Regret": "Pişman olmak",
    "Relate": "Bağlantı kurmak",
    "Relax": "Rahatlamak",
    "Relieve": "Yüreğine su serpmek",
    "Rely": "Güvenmek",
    "Remain": "Geriye kalmak",
    "Remember": "Hatırlamak",
    "Remind": "Hatırlatmak",
    "Repair": "Tamir etmek",
    "Replace": "Yerine geçmek",
    "Represent": "Temsil etmek",
    "Require": "Gerek, ihtiyaç duymak",
    "Resent": "Alınmak, içerlemek",
    "Resist": "Dayanmak, direnmek",
    "Retire": "Emekli olmak",
    "Ride": "Binmek",
    "Ring": "Çalmak (telefon/zil)",
    "Rise": "Doğmak, yükselmek",
    "Risk": "Göze almak",
    "Run": "Koşmak",
    "Satisfy": "Tatmin etmek",
    "Say": "Söylemek",
    "Scrub": "Ovmak",
    "See": "Görmek",
    "Seem": "Gözükmek",
    "Sell": "Satmak",
    "Send": "Göndermek",
    "Serve": "Hizmet etmek",
    "Set": "Kurmak",
    "Settle": "Yerleşmek, oturtmak",
    "Sew": "Dikiş dikmek",
    "Shake": "Sallamak",
    "Shine": "Parıldamak, parlamak",
    "Shoot": "Film çekmek, ateş etmek",
    "Show": "Göstermek",
    "Shut": "Kapatmak",
    "Sink": "Suya batmak, batırmak",
    "Sit": "Oturmak",
    "Sing": "Şarkı söylemek",
    "Ski": "Kayak yapmak",
    "Sleep": "Uyumak",
    "Slice": "Dilimlemek",
    "Smell": "Koklamak",
    "Snore": "Horlamak, Hırıldamak",
    "Solve": "Çözmek",
    "Sort": "Sınıflandırmak",
    "Sound": "Ses çıkarmak",
    "Spare": "Ayırmak, yedek olmak",
    "Speak": "Konuşmak",
    "Specify": "Belirtmek",
    "Spell": "Hecelemek",
    "Spend": "Harcamak, geçirmek (vakit)",
    "Spill": "Dökmek",
    "Spoil": "Berbat etmek",
    "Spread": "Yayılmak, yaymak",
    "Squeeze": "Sıkmak",
    "Stand": "Dikilmek, ayakta durmak",
    "Start": "Başlamak",
    "Stay": "Kalmak",
    "Steal": "Çalmak",
    "Stick": "Yapıştırmak",
    "Stink": "Kokmak",
    "Stop": "Durdurmak",
    "Strengthen": "Güçlendirmek",
    "Study": "Çalışmak, okumak",
    "Succeed": "Başarmak",
    "Suffer": "Katlanmak, çekmek",
    "Suggest": "Önermek",
    "Suit": "Uymak, yakışmak",
    "Suppose": "Farzetmek",
    "Surprise": "Saşırtmak",
    "Survive": "Hayatta kalmak",
    "Suspect": "Şüphelenmek",
    "Suspend": "Askıya almak",
    "Sustain": "Devam ettirmek, sürdürmek",
    "Swear": "Yemin etmek",
    "Sweep": "Süpürmek",
    "Swim": "Yüzmek",
    "Swing": "Sallamak, sarkmak",
    "Take": "Almak",
    "Talk": "Konuşmak",
    "Taste": "Tatmak",
    "Tax": "Vergilendirmek",
    "Teach": "Öğretmek",
    "Tear": "Yırtmak",
    "Tell": "Söylemek, anlatmak",
    "Test": "Test etmek, sınamak",
    "Thank": "Teşekkür etmek",
    "Think": "Düşünmek",
    "Thrive": "Gelişmek, büyümek",
    "Throw": "Atmak",
    "Tie": "Bağlamak, bağlamak",
    "Toast": "Tosta yapmak",
    "Touch": "Dokunmak",
    "Train": "Eğitmek",
    "Translate": "Cevirmek",
    "Travel": "Seyahat etmek",
    "Treat": "Tedavi etmek, davranmak",
    "Try": "Denemek",
    "Turn": "Dönmek, çevirmek",
    "Understand": "Anlamak",
    "Undertake": "Üstlenmek",
    "Use": "Kullanmak",
    "Value": "Değer vermek",
    "View": "İzlemek",
    "Visit": "Ziyaret etmek",
    "Voice": "Ses vermek",
    "Vote": "Oy kullanmak",
    "Wait": "Beklemek",
    "Wake": "Uyanmak",
    "Walk": "Yürümek",
    "Want": "İstemek",
    "Warm": "Isıtmak",
    "Wash": "Yıkamak",
    "Watch": "İzlemek",
    "Wear": "Giyinmek",
    "Weep": "Ağlamak",
    "Weigh": "Tartmak",
    "Win": "Kazanmak",
    "Wish": "Dilemek",
    "Work": "Çalışmak",
    "Worry": "Endişelenmek",
    "Write": "Yazmak"
            
    # You can add more words
}

class WordGameApp:
    def __init__(self, root):
        self.root = root
        self.root.title("English-Turkish Word Game")

        self.word_label = tk.Label(root, text="", font=("Helvetica", 24))
        self.word_label.pack(pady=20)

        self.answer_entry = tk.Entry(root, font=("Helvetica", 16))
        self.answer_entry.pack(pady=10)
        self.answer_entry.bind("<Return>", lambda event: self.check_answer())

        self.submit_button = tk.Button(root, text="Check Answer", command=self.check_answer)
        self.submit_button.pack()

        self.play_again_button = tk.Button(root, text="Play Again", command=self.play_again, state=tk.DISABLED)
        self.play_again_button.pack()

        self.random_word = ""
        self.correct_answer = ""

        self.ask_new_question()

    def ask_new_question(self):
        self.random_word = random.choice(list(word_dict.keys()))
        self.correct_answer = word_dict[self.random_word]
        self.word_label.config(text=f"What is the Turkish translation of '{self.random_word}'?")
        self.answer_entry.delete(0, tk.END)
        self.play_again_button.config(state=tk.DISABLED)

    def check_answer(self):
        user_answer = self.answer_entry.get().strip().lower()
        if user_answer == self.correct_answer.lower():
            messagebox.showinfo("Correct!", "Great job!")
        else:
            messagebox.showerror("Incorrect", f"Sorry, the correct answer is '{self.correct_answer}'.")
        self.play_again_button.config(state=tk.NORMAL)

    def play_again(self):
        self.ask_new_question()

if __name__ == "__main__":
    root = tk.Tk()
    app = WordGameApp(root)
    root.mainloop()
# interface created with chatgpt